### ISSUE TITLE
Step Definition creation fails with ClassCastException

### ISSUE THREAD

**Issue by dave00galloway** [jlagerweij/cucumber-kotlin#16]
Created a new step definition file and got an IDE Fatal Error.

using:

`
IntelliJ IDEA 2019.1.3  Build #IC-191.7479.19
JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
OS: Mac OS X
Plugin to blame: Cucumber for Kotlin version: 1.1.1 
`

<img width="856" alt="Screenshot 2020-03-03 at 14 00 26" src="https://user-images.githubusercontent.com/6429351/75782798-68cc9f80-5d57-11ea-89bf-51a90dc612bf.png">

`
java.lang.ClassCastException: com.intellij.psi.impl.file.PsiBinaryFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at net.lagerwey.plugins.cucumber.kotlin.KotlinStepDefinitionCreator.createStepDefinitionContainer(KotlinStepDefinitionCreator.kt:26)
	at org.jetbrains.plugins.cucumber.steps.CucumberStepsIndex.createStepDefinitionFile(CucumberStepsIndex.java:72)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.lambda$null$0(CucumberCreateStepFixBase.java:151)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.lambda$createStepDefinitionFile$1(CucumberCreateStepFixBase.java:145)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:263)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:319)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:321)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:353)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.createStepDefinitionFile(CucumberCreateStepFixBase.java:144)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.createFileOrStepDefinition(CucumberCreateStepFixBase.java:169)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFix.createStepOrSteps(CucumberCreateStepFix.java:20)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase$1.lambda$onChosen$0(CucumberCreateStepFixBase.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1416)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3080)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:159)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:111)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:58)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1412)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:306)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:136)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:105)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:214)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:105)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:442)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:395)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:336)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:249)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:358)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:114)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:150)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:86)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
`

extra info from intelliJ log:-

`
2020-03-03 13:53:42,162 [517737766]   INFO - rationStore.ComponentStoreImpl - Saving Project '<checkout-dir>' acceptanceRunManager took 16 ms 
2020-03-03 13:53:42,206 [517737810]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 127 ms 
2020-03-03 13:55:51,244 [517866848]  ERROR - api.util.objectTree.ObjectTree - com.intellij.psi.impl.file.PsiBinaryFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile 
java.lang.ClassCastException: com.intellij.psi.impl.file.PsiBinaryFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at net.lagerwey.plugins.cucumber.kotlin.KotlinStepDefinitionCreator.createStepDefinitionContainer(KotlinStepDefinitionCreator.kt:26)
	at org.jetbrains.plugins.cucumber.steps.CucumberStepsIndex.createStepDefinitionFile(CucumberStepsIndex.java:72)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.lambda$null$0(CucumberCreateStepFixBase.java:151)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.lambda$createStepDefinitionFile$1(CucumberCreateStepFixBase.java:145)
	at com.intellij.openapi.command.WriteCommandAction.lambda$runWriteCommandAction$5(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl$1.run(WriteCommandAction.java:124)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:35)
	at com.intellij.openapi.command.WriteCommandAction.lambda$null$1(WriteCommandAction.java:263)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1054)
	at com.intellij.openapi.command.WriteCommandAction.lambda$performWriteCommandAction$2(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.lambda$doExecuteCommand$4(WriteCommandAction.java:319)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:188)
	at com.intellij.openapi.command.WriteCommandAction.doExecuteCommand(WriteCommandAction.java:321)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:262)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:244)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:126)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:361)
	at com.intellij.openapi.command.WriteCommandAction.runWriteCommandAction(WriteCommandAction.java:353)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.createStepDefinitionFile(CucumberCreateStepFixBase.java:144)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase.createFileOrStepDefinition(CucumberCreateStepFixBase.java:169)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFix.createStepOrSteps(CucumberCreateStepFix.java:20)
	at org.jetbrains.plugins.cucumber.inspections.CucumberCreateStepFixBase$1.lambda$onChosen$0(CucumberCreateStepFixBase.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:195)
	at com.intellij.ui.popup.AbstractPopup.lambda$dispose$13(AbstractPopup.java:1416)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:3080)
	at com.intellij.ide.IdeEventQueue.ifFocusEventsInTheQueue(IdeEventQueue.java:159)
	at com.intellij.ide.IdeEventQueue.executeWhenAllFocusEventsLeftTheQueue(IdeEventQueue.java:111)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:179)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.doWhenFocusSettlesDown(IdeFocusManagerImpl.java:58)
	at com.intellij.ui.popup.AbstractPopup.dispose(AbstractPopup.java:1412)
	at com.intellij.ui.popup.WizardPopup.dispose(WizardPopup.java:160)
	at com.intellij.ui.popup.list.ListPopupImpl.dispose(ListPopupImpl.java:306)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:48)
	at com.intellij.openapi.util.Disposer$1.execute(Disposer.java:44)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:136)
	at com.intellij.openapi.util.objectTree.ObjectNode$1.execute(ObjectNode.java:105)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeActionWithRecursiveGuard(ObjectTree.java:214)
	at com.intellij.openapi.util.objectTree.ObjectNode.execute(ObjectNode.java:105)
	at com.intellij.openapi.util.objectTree.ObjectTree.executeAll(ObjectTree.java:162)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:129)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:125)
	at com.intellij.ui.popup.WizardPopup.disposeAllParents(WizardPopup.java:263)
	at com.intellij.ui.popup.list.ListPopupImpl.handleNextStep(ListPopupImpl.java:442)
	at com.intellij.ui.popup.list.ListPopupImpl._handleSelect(ListPopupImpl.java:395)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:336)
	at com.intellij.ui.popup.list.ListPopupImpl$1.actionPerformed(ListPopupImpl.java:249)
	at com.intellij.ui.popup.WizardPopup.proceedKeyEvent(WizardPopup.java:378)
	at com.intellij.ui.popup.WizardPopup.dispatch(WizardPopup.java:358)
	at com.intellij.ui.popup.PopupDispatcher.dispatchKeyEvent(PopupDispatcher.java:114)
	at com.intellij.ui.popup.PopupDispatcher.dispatch(PopupDispatcher.java:150)
	at com.intellij.ide.IdePopupManager.dispatch(IdePopupManager.java:86)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:629)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:373)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2020-03-03 13:55:51,248 [517866852]  ERROR - api.util.objectTree.ObjectTree - IntelliJ IDEA 2019.1.3  Build #IC-191.7479.19 
2020-03-03 13:55:51,248 [517866852]  ERROR - api.util.objectTree.ObjectTree - JDK: 1.8.0_202-release; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-03-03 13:55:51,248 [517866852]  ERROR - api.util.objectTree.ObjectTree - OS: Mac OS X 
2020-03-03 13:55:51,250 [517866854]  ERROR - api.util.objectTree.ObjectTree - Plugin to blame: Cucumber for Kotlin version: 1.1.1 
2020-03-03 13:55:51,250 [517866854]  ERROR - api.util.objectTree.ObjectTree - Last Action: EditorBackSpace 
2020-03-03 13:55:51,318 [517866922]   WARN - llij.ide.plugins.PluginManager - Material Color Palette not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,318 [517866922]   WARN - llij.ide.plugins.PluginManager - Material Design Dark-Theme not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Logsdk not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Clean Architecture for Flutter not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Android Resource Value Viewer not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - TenBis (10bis.co.il) Food Delivery Button not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Android SecuRefactor not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Gherkin not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Generate Module From Template not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Flutter Intl not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - Socket Client not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - IntelliJ API Watcher not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:51,319 [517866923]   WARN - llij.ide.plugins.PluginManager - OSGi not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,320 [517866924]   WARN - llij.ide.plugins.PluginManager - hybris integration not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:51,320 [517866924]   WARN - llij.ide.plugins.PluginManager - Flow not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,320 [517866924]   WARN - llij.ide.plugins.PluginManager - Python Community Edition not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,320 [517866924]   WARN - llij.ide.plugins.PluginManager - Flutter not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,320 [517866924]   WARN - llij.ide.plugins.PluginManager - JIRA Todo Tasks not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,320 [517866924]   WARN - llij.ide.plugins.PluginManager - JetForcer | The Smartest Force.com IDE not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,321 [517866925]   WARN - llij.ide.plugins.PluginManager - Layout Opener not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,321 [517866925]   WARN - llij.ide.plugins.PluginManager - Android Resource Tool not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,321 [517866925]   WARN - llij.ide.plugins.PluginManager - Kotlinize PR not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,321 [517866925]   WARN - llij.ide.plugins.PluginManager - Intechsoft Model Handler not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,321 [517866925]   WARN - llij.ide.plugins.PluginManager - LocallyDynamic not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,321 [517866925]   WARN - llij.ide.plugins.PluginManager - Android Resource Manager not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:51,365 [517866969]   INFO -  #git4idea.commands.GitHandler - [../../../rs-test] git -c core.quotepath=false -c log.showSignature=false add --ignore-errors -A -- <project-dir>/src/cucumberTest/resources/NewCustomeStepDefFile 
2020-03-03 13:55:52,009 [517867613]   WARN - llij.ide.plugins.PluginManager - Material Color Palette not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,009 [517867613]   WARN - llij.ide.plugins.PluginManager - Material Design Dark-Theme not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:52,009 [517867613]   WARN - llij.ide.plugins.PluginManager - Logsdk not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,009 [517867613]   WARN - llij.ide.plugins.PluginManager - Clean Architecture for Flutter not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:52,009 [517867613]   WARN - llij.ide.plugins.PluginManager - Android Resource Value Viewer not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - TenBis (10bis.co.il) Food Delivery Button not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Android SecuRefactor not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Gherkin not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Generate Module From Template not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Flutter Intl not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Socket Client not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - IntelliJ API Watcher not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - OSGi not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - hybris integration not loaded: since build 191.8026.42 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Flow not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Python Community Edition not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,010 [517867614]   WARN - llij.ide.plugins.PluginManager - Flutter not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - JIRA Todo Tasks not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - JetForcer | The Smartest Force.com IDE not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - Layout Opener not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - Android Resource Tool not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - Kotlinize PR not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - Intechsoft Model Handler not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - LocallyDynamic not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,011 [517867615]   WARN - llij.ide.plugins.PluginManager - Android Resource Manager not loaded: since build 191.8026 > IC-191.7479.19 
2020-03-03 13:55:52,222 [517867826]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android/sys-img2-1.xml 
2020-03-03 13:55:52,222 [517867826]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-automotive/sys-img2-1.xml 
2020-03-03 13:55:52,222 [517867826]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-wear/sys-img2-1.xml 
2020-03-03 13:55:52,222 [517867826]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-wear-cn/sys-img2-1.xml 
2020-03-03 13:55:52,222 [517867826]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/android-tv/sys-img2-1.xml 
2020-03-03 13:55:52,222 [517867826]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/google_apis/sys-img2-1.xml 
2020-03-03 13:55:52,223 [517867827]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/addon2-1.xml 
2020-03-03 13:55:52,223 [517867827]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/glass/addon2-1.xml 
2020-03-03 13:55:52,223 [517867827]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/repository2-1.xml 
2020-03-03 13:55:52,223 [517867827]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/extras/intel/addon2-1.xml 
2020-03-03 13:55:52,225 [517867829]   INFO - dea.updater.SdkComponentSource - Downloading https://dl.google.com/android/repository/sys-img/google_apis_playstore/sys-img2-1.xml 
2020-03-03 13:56:35,627 [517911231]   INFO - rationStore.ComponentStoreImpl - Saving Project '<checkout-dir>' acceptanceRunManager took 23 ms 
2020-03-03 13:56:35,639 [517911243]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 119 ms 
2020-03-03 13:58:52,073 [518047677]   INFO - rationStore.ComponentStoreImpl - Saving Project '<checkout-dir>' acceptanceRunManager took 15 ms 
2020-03-03 13:58:52,104 [518047708]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 84 ms 
2020-03-03 13:59:14,222 [518069826]   INFO - rationStore.ComponentStoreImpl - Saving Project '<checkout-dir>' acceptanceRunManager took 14 ms 
2020-03-03 13:59:14,228 [518069832]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 42 ms 
2020-03-03 14:01:49,517 [518225121]   INFO - rationStore.ComponentStoreImpl - Saving Project '<checkout-dir>' acceptanceRunManager took 15 ms 
2020-03-03 14:01:49,525 [518225129]   INFO - mponents.impl.stores.StoreUtil - saveProjectsAndApp took 46 ms 

`

**Comment by jlagerweij** [comment]
The plugin now only works with versions of IntellJ that the Gherkin plugin also works with. This should now be fixed.
