### ISSUE TITLE
2020.3 plugin version is incompatible with Java 8 runtime

### ISSUE THREAD

**Issue by igeneralov** [jlagerweij/cucumber-kotlin#28]
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:63)
Caused by: java.lang.UnsupportedClassVersionError: org/jetbrains/plugins/cucumber/java/run/CucumberJvm4SMFormatter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
Seems, that the plugin was compiled using JDK 11, which is nice, but makes it impossible to be used by JDK 8 runtime, which is still officially supported, btw.

Is it possible, to compile the plugin in JDK 8 compatible way?

**Comment by jlagerweij** [comment]
The CucumberJvm4SMFormatter is part of cucumber-jvm-formatter4 and is maintained by JetBrains. Please take this up with them.
