### ISSUE TITLE
Navigate to step def from feature sometimes fails and gives "Convert to scenario outline" option instead

### ISSUE THREAD

**Issue by dave99galloway** [jlagerweij/cucumber-kotlin#31]
IDEA warned me this was being thrown when step def navigation failed. expecting a prompt to create a new one, but got
Convert to scenario outline" option instead .

`
IntelliJ IDEA 2020.2.4 (Community Edition)
Build #IC-202.8194.7, built on November 24, 2020
Runtime version: 1.8.0_202-release-b1491 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.7
GC: ParNew, ConcurrentMarkSweep
Memory: 1450M
Cores: 8
Registry: terminal.buffer.max.lines.count=100000, debugger.watches.in.variables=false
Non-Bundled Plugins: PlantUML integration, com.github.shiraji.pluginimporterexporter, com.ivanovych666.intellij.plugin.jsonsorter, com.jetbrains.jbre.bintray.downloader, mobi.hsz.idea.gitignore, Docker, org.sonarlint.idea, Spock Framework Enhancements, org.jetbrains.kotlin, cn.wjdghd.unique.plugin.id, gherkin, cucumber-java, cucumber-groovy, net.lagerwey.cucumber-kotlin, PythonCore, com.jetbrains.edu, net.ashald.envfile
`

`kotlin.KotlinNullPointerException
	at net.lagerwey.plugins.cucumber.kotlin.search.StepDeclarationSearcher.findStepDeclaration(StepDeclarationSearcher.kt:41)
	at net.lagerwey.plugins.cucumber.kotlin.search.StepDeclarationSearcher.access$findStepDeclaration(StepDeclarationSearcher.kt:19)
	at net.lagerwey.plugins.cucumber.kotlin.search.StepDeclarationSearcher$findDeclarationsAt$stepDeclaration$1.invoke(StepDeclarationSearcher.kt:27)
	at net.lagerwey.plugins.cucumber.kotlin.search.StepDeclarationSearcher$findDeclarationsAt$stepDeclaration$1.invoke(StepDeclarationSearcher.kt:19)
	at net.lagerwey.plugins.cucumber.kotlin.UtilKt.inReadAction(Util.kt:8)
	at net.lagerwey.plugins.cucumber.kotlin.search.StepDeclarationSearcher.findDeclarationsAt(StepDeclarationSearcher.kt:25)
	at com.intellij.model.psi.impl.DefaultPsiSymbolDeclarationProvider.getDeclarations(DefaultPsiSymbolDeclarationProvider.kt:23)
	at com.intellij.model.psi.impl.Declarations.declarationsInElement(declarations.kt:35)
	at com.intellij.model.psi.impl.Declarations.allDeclarationsAround(declarations.kt:21)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:113)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:34)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:233)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:225)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:90)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$1(PassExecutorService.java:399)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1110)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:392)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:629)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:391)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:367)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:170)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:365)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:181)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`

**Comment by jlagerweij** [comment]
This should be fixed in version 2021.1.0
