### ISSUE TITLE
Plugin fails in IDEA 19.1 due to NoSuchMethodError for CucumberUtil.isCucumberExpression

### ISSUE THREAD

**Issue by evestera** [jlagerweij/cucumber-kotlin#7]
`CucumberUtil.isCucumberExpression` was deleted from the bundled cucumber plugin in [301862aec1a10ef034b2bb116c091b25aebd1110](https://github.com/JetBrains/intellij-plugins/commit/301862aec1a10ef034b2bb116c091b25aebd1110), and as such, from IDEA 19.1. This causes the plugin to fail in 19.1 since the method is used in `KotlinStepDefinition.getCucumberRegexFromElement`.

The method was restored in [9338364a067f03bc16105d3fbd7fca5f199c84d6](https://github.com/JetBrains/intellij-plugins/commit/9338364a067f03bc16105d3fbd7fca5f199c84d6), but has not made it into a release yet.

**Comment by evestera** [comment]
I'll have a look at a fix as soon as I have the time, hopefully tomorrow. Perhaps it is best to just vendor the necessary parts of `CucumberUtil`, at least temporarily? Any opinions, @jlagerweij?

**Comment by jlagerweij** [comment]
Yes, I agree. 
I tested this on Idea 2018.3, but not on 2019.1, so did not catch this removal.
Would be great if you could pick this up.

**Comment by dave00galloway** [comment]
also just hit this in 2019.1.3.  It occurs when viewing feature files.

 here's the full stacktrace FYI 

`java.lang.NoSuchMethodError: org.jetbrains.plugins.cucumber.CucumberUtil.isCucumberExpression(Ljava/lang/String;)Z
	at net.lagerwey.plugins.cucumber.kotlin.steps.KotlinStepDefinition.getCucumberRegexFromElement(KotlinStepDefinition.kt:15)
	at org.jetbrains.plugins.cucumber.steps.AbstractStepDefinition.getCucumberRegex(AbstractStepDefinition.java:96)
	at org.jetbrains.plugins.cucumber.steps.AbstractStepDefinition.getPattern(AbstractStepDefinition.java:72)
	at org.jetbrains.plugins.cucumber.steps.AbstractStepDefinition.matches(AbstractStepDefinition.java:47)
	at org.jetbrains.plugins.cucumber.steps.CucumberStepsIndex.findStepDefinitions(CucumberStepsIndex.java:123)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolveToDefinitions(CucumberStepReference.java:137)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolveToDefinition(CucumberStepReference.java:126)
	at org.jetbrains.plugins.cucumber.psi.annotator.GherkinAnnotatorVisitor.visitStep(GherkinAnnotatorVisitor.java:57)
	at org.jetbrains.plugins.cucumber.psi.impl.GherkinStepImpl.acceptGherkin(GherkinStepImpl.java:106)
	at org.jetbrains.plugins.cucumber.psi.impl.GherkinPsiElementBase.accept(GherkinPsiElementBase.java:70)
	at org.jetbrains.plugins.cucumber.psi.annotator.GherkinAnnotator.annotate(GherkinAnnotator.java:16)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:284)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:281)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:225)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)`
