### ISSUE TITLE
QUERY: v1.1.1 availability

### ISSUE THREAD

**Issue by nheitz** [jlagerweij/cucumber-kotlin#9]
Hi...Is the 1.1.1 version for IDEA available in marketplace?

Cucumber for kotlin stopped working this morning after the latest IDEA update.

```
java.lang.NoSuchMethodError: org.jetbrains.plugins.cucumber.CucumberUtil.isCucumberExpression(Ljava/lang/String;)Z
	at net.lagerwey.plugins.cucumber.kotlin.steps.KotlinStepDefinition.getCucumberRegexFromElement(KotlinStepDefinition.kt:15)
	at org.jetbrains.plugins.cucumber.steps.AbstractStepDefinition.getCucumberRegex(AbstractStepDefinition.java:96)
	at org.jetbrains.plugins.cucumber.steps.AbstractStepDefinition.getPattern(AbstractStepDefinition.java:72)
	at org.jetbrains.plugins.cucumber.steps.AbstractStepDefinition.matches(AbstractStepDefinition.java:47)
	at org.jetbrains.plugins.cucumber.steps.CucumberStepsIndex.findStepDefinitions(CucumberStepsIndex.java:123)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolveToDefinitions(CucumberStepReference.java:137)
	at org.jetbrains.plugins.cucumber.steps.reference.CucumberStepReference.resolveToDefinition(CucumberStepReference.java:126)
	at org.jetbrains.plugins.cucumber.inspections.CucumberStepInspection$1.visitStep(CucumberStepInspection.java:54)
	at org.jetbrains.plugins.cucumber.psi.impl.GherkinStepImpl.acceptGherkin(GherkinStepImpl.java:106)
	at org.jetbrains.plugins.cucumber.psi.impl.GherkinPsiElementBase.accept(GherkinPsiElementBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:295)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:260)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by jlagerweij** [comment]
It has been submitted to JetBrains and is awaiting approval from them.

**Comment by jlagerweij** [comment]
Version 1.1.1 has just been approved by JetBrains and is now available.
